version: '2'
services:
  web:
    build: .
    ports:
      - "8088:8088"
    volumes:
      - .:/app
    tty: true
    privileged: true
    command: > 
      bash -c "
        cd /app;
        composer install;
        tail -f /dev/null;
        "
